services:
  postgres:
    image: postgres:16
    container_name: cinema_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: cinema_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./cinema-backend
    container_name: cinema_backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: cinema_db
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    working_dir: /app

  frontend:
    build:
      context: ./cinema-admin-app
    container_name: cinema_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data: