openapi: 3.0.0
info:
  title: Cinema Admin API
  version: 1.0.0
  description: API documentation for Cinema Admin App

servers:
  - url: http://localhost:4000

paths:
  /users/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User registered

  /users/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful

  /admins/login:
    post:
      summary: Admin login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful

  /cinemas:
    get:
      summary: List all cinemas
      responses:
        '200':
          description: A list of cinemas

  /cinemas/{cinemaId}/auditoriums:
    get:
      summary: List auditoriums for a cinema
      parameters:
        - in: path
          name: cinemaId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A list of auditoriums

    post:
      summary: Add auditorium to a cinema
      parameters:
        - in: path
          name: cinemaId
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                capacity:
                  type: integer
      responses:
        '201':
          description: Auditorium created

  /auditoriums/{auditoriumId}:
    patch:
      summary: Edit auditorium
      parameters:
        - in: path
          name: auditoriumId
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                capacity:
                  type: integer
      responses:
        '200':
          description: Auditorium updated

    delete:
      summary: Delete auditorium
      parameters:
        - in: path
          name: auditoriumId
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Auditorium deleted

  /cinemas/{cinemaId}/showtimes:
    get:
      summary: List showtimes for a cinema
      parameters:
        - in: path
          name: cinemaId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A list of showtimes

    post:
      summary: Add showtime to a cinema
      parameters:
        - in: path
          name: cinemaId
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                auditoriumId:
                  type: integer
                movie_title:
                  type: string
                start_time:
                  type: string
                  format: date-time
                price:
                  type: number
      responses:
        '201':
          description: Showtime created

  /cinemas/{cinemaId}/showtimes/{showtimeId}:
    patch:
      summary: Edit showtime
      parameters:
        - in: path
          name: cinemaId
          required: true
          schema:
            type: integer
        - in: path
          name: showtimeId
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                movie_title:
                  type: string
                start_time:
                  type: string
                  format: date-time
                price:
                  type: number
      responses:
        '200':
          description: Showtime updated

  /showtimes/{showtimeId}:
    delete:
      summary: Delete showtime
      parameters:
        - in: path
          name: showtimeId
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Showtime deleted